const STATE = {questions:[],quizSet:[],idx:0,correct:0,combo:0,earnedXp:0,weeklyPoints:0,ready:false,level:1};
const $=s=>document.querySelector(s);
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(id).classList.remove('hidden');}
function setAvatarByLevel(lv){const img=$('#avatar');if(lv>=10)img.src='assets/avatar_stage3.svg';else if(lv>=5)img.src='assets/avatar_stage2.svg';else img.src='assets/avatar_stage1.svg';}
async function getSheetUrl(){return localStorage.getItem('sheetUrl')||'';}
async function saveSheetUrl(){const url=$('#sheetUrl').value.trim();localStorage.setItem('sheetUrl',url);alert('シートURLを保存しました。ページを更新すると反映されます。');}
function loadLocal(){STATE.weeklyPoints=Number(localStorage.getItem('weeklyPoints')||0);STATE.level=Number(localStorage.getItem('level')||1);$('#weeklyPoints').textContent=STATE.weeklyPoints;$('#todayXp').textContent=Number(localStorage.getItem('todayXp')||0);$('#combo').textContent=0;setAvatarByLevel(STATE.level);}
function saveProgress(){localStorage.setItem('weeklyPoints',String(STATE.weeklyPoints));localStorage.setItem('level',String(STATE.level));}
function pick10(arr){const pool=[...arr],out=[];while(out.length<10&&pool.length){out.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0]);}return out;}
async function loadQuestions(){ $('#startQuizBtn').disabled=true; $('#startQuizBtn').textContent='読み込み中…'; let url=await getSheetUrl(); let useLocal=false; if(!url){url='assets/questions.csv';useLocal=true;} try{ const res=await fetch(url,{cache:'no-store'}); if(!res.ok) throw new Error('CSV fetch failed:'+res.status); const csv=await res.text(); return new Promise(resolve=>Papa.parse(csv,{header:true,complete:p=>{resolve(p.data.filter(r=>r.id&&String(r.id).trim().length>0));}})); }catch(e){ console.error(e); if(!useLocal){ try{ const r2=await fetch('assets/questions.csv',{cache:'no-store'}); const t2=await r2.text(); return new Promise(resolve=>Papa.parse(t2,{header:true,complete:p=>{resolve(p.data.filter(r=>r.id&&String(r.id).trim().length>0));}})); }catch(e2){ console.error(e2); alert('問題の読み込みに失敗。シートURL/CSVを確認。'); return []; } } return []; } finally { $('#startQuizBtn').disabled=false; $('#startQuizBtn').textContent='クエストを始める'; }}
function renderQuestion(){const q=STATE.quizSet[STATE.idx];$('#qProgress').textContent=`${STATE.idx+1} / ${STATE.quizSet.length}`;$('#qTag').textContent=q['タグ']||'';$('#qText').textContent=q['問題文']||'(問題文未設定)';$('#feedback').textContent='';$('#nextBtn').disabled=true;const wrap=$('#choices');wrap.innerHTML='';['A','B','C','D'].forEach(l=>{const txt=q['選択肢'+l];if(!txt)return;const btn=document.createElement('button');btn.className='choice';btn.textContent=txt;btn.addEventListener('click',()=>onAnswer(l,btn,q));wrap.appendChild(btn);});}
function onAnswer(lab,btn,q){const correct=q['正解'];document.querySelectorAll('.choice').forEach(e=>e.disabled=true);if(lab===correct){btn.classList.add('correct');STATE.correct+=1;STATE.combo+=1;const mult=STATE.combo>=10?2.0:STATE.combo>=5?1.5:1.0;const gained=Math.round(10*mult);STATE.earnedXp+=gained;$('#feedback').textContent=`正解！ +${gained} XP（コンボ×${mult.toFixed(1)}）`;}else{btn.classList.add('wrong');STATE.combo=0;$('#feedback').textContent=`不正解… 解説：${q['解説']||'—'}`;}document.querySelectorAll('.choice').forEach(e=>{if(e.textContent===q['選択肢'+correct])e.classList.add('correct');});$('#combo').textContent=STATE.combo;$('#nextBtn').disabled=false;}
function nextQuestion(){STATE.idx+=1;if(STATE.idx>=STATE.quizSet.length){$('#correctCount').textContent=STATE.correct;$('#earnedXp').textContent=STATE.earnedXp;STATE.weeklyPoints+=STATE.earnedXp;const prev=STATE.level;STATE.level+=Math.floor(STATE.earnedXp/100);if(STATE.level!==prev)setAvatarByLevel(STATE.level);saveProgress();$('#finalWeeklyPoints').textContent=STATE.weeklyPoints;const today=Number(localStorage.getItem('todayXp')||0)+STATE.earnedXp;localStorage.setItem('todayXp',String(today));$('#todayXp').textContent=today;showView('#resultView');}else{renderQuestion();}}
function quitQuiz(){showView('#homeView');}function backHome(){showView('#homeView');}
window.addEventListener('DOMContentLoaded',async()=>{loadLocal();$('#saveSheetBtn').addEventListener('click',saveSheetUrl);$('#sheetUrl').value=await getSheetUrl();STATE.questions=await loadQuestions();STATE.ready=true;$('#reviewCount').textContent=0;$('#startQuizBtn').addEventListener('click',()=>{if(!STATE.ready||!STATE.questions.length){alert('問題がまだ読み込めていません。');return;}STATE.quizSet=pick10(STATE.questions);STATE.idx=0;STATE.correct=0;STATE.combo=0;STATE.earnedXp=0;renderQuestion();showView('#quizView');});$('#nextBtn').addEventListener('click',nextQuestion);$('#quitBtn').addEventListener('click',quitQuiz);$('#backHomeBtn').addEventListener('click',backHome);});